// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import MapboxController from "./mapbox_controller"
application.register("mapbox", MapboxController)
